module.exports = function(db) {

	db.Country.create({countryCode:  'AD', countryName: 'Andorra', sortOrder: '1', isActive: '1'});
  db.Country.create({countryCode:  'AE', countryName: 'United Arab Emirates', sortOrder: '2', isActive: '1'});
  db.Country.create({countryCode:  'AF', countryName: 'Afghanistan', sortOrder: '3', isActive: '1'});
  db.Country.create({countryCode:  'AG', countryName: 'Antigua and Barbuda', sortOrder: '4', isActive: '1'});
  db.Country.create({countryCode:  'AI', countryName: 'Anguilla', sortOrder: '5', isActive: '1'});
  db.Country.create({countryCode:  'AL', countryName: 'Albania', sortOrder: '6', isActive: '1'});
  db.Country.create({countryCode:  'AM', countryName: 'Armenia', sortOrder: '7', isActive: '1'});
  db.Country.create({countryCode:  'AN', countryName: 'Netherlands Antilles', sortOrder: '8', isActive: '1'});
  db.Country.create({countryCode:  'AO', countryName: 'Angola', sortOrder: '9', isActive: '1'});
  db.Country.create({countryCode:  'AQ', countryName: 'Antarctica', sortOrder: '10', isActive: '1'});
  db.Country.create({countryCode:  'AR', countryName: 'Argentina', sortOrder: '11', isActive: '1'});
  db.Country.create({countryCode:  'AS', countryName: 'American Samoa', sortOrder: '12', isActive: '1'});
  db.Country.create({countryCode:  'AT', countryName: 'Austria', sortOrder: '13', isActive: '1'});
  db.Country.create({countryCode:  'AU', countryName: 'Australia', sortOrder: '14', isActive: '1'});
  db.Country.create({countryCode:  'AW', countryName: 'Aruba', sortOrder: '15', isActive: '1'});
  db.Country.create({countryCode:  'AZ', countryName: 'Azerbaijan', sortOrder: '16', isActive: '1'});
  db.Country.create({countryCode:  'BA', countryName: 'Bosnia and Herzegovina', sortOrder: '17', isActive: '1'});
  db.Country.create({countryCode:  'BB', countryName: 'Barbados', sortOrder: '18', isActive: '1'});
  db.Country.create({countryCode:  'BD', countryName: 'Bangladesh', sortOrder: '19', isActive: '1'});
  db.Country.create({countryCode:  'BE', countryName: 'Belgium', sortOrder: '20', isActive: '1'});
  db.Country.create({countryCode:  'BF', countryName: 'Burkina Faso', sortOrder: '21', isActive: '1'});
  db.Country.create({countryCode:  'BG', countryName: 'Bulgaria', sortOrder: '22', isActive: '1'});
  db.Country.create({countryCode:  'BH', countryName: 'Bahrain', sortOrder: '23', isActive: '1'});
  db.Country.create({countryCode:  'BI', countryName: 'Burundi', sortOrder: '24', isActive: '1'});
  db.Country.create({countryCode:  'BJ', countryName: 'Benin', sortOrder: '25', isActive: '1'});
  db.Country.create({countryCode:  'BM', countryName: 'Bermuda', sortOrder: '26', isActive: '1'});
  db.Country.create({countryCode:  'BN', countryName: 'Brunei', sortOrder: '27', isActive: '1'});
  db.Country.create({countryCode:  'BO', countryName: 'Bolivia', sortOrder: '28', isActive: '1'});
  db.Country.create({countryCode:  'BR', countryName: 'Brazil', sortOrder: '29', isActive: '1'});
  db.Country.create({countryCode:  'BS', countryName: 'Bahamas, The', sortOrder: '30', isActive: '1'});
  db.Country.create({countryCode:  'BT', countryName: 'Bhutan', sortOrder: '31', isActive: '1'});
  db.Country.create({countryCode:  'BV', countryName: 'Bouvet Island', sortOrder: '32', isActive: '1'});
  db.Country.create({countryCode:  'BW', countryName: 'Botswana', sortOrder: '33', isActive: '1'});
  db.Country.create({countryCode:  'BY', countryName: 'Belarus', sortOrder: '34', isActive: '1'});
  db.Country.create({countryCode:  'BZ', countryName: 'Belize', sortOrder: '35', isActive: '1'});
  db.Country.create({countryCode:  'CA', countryName: 'Canada', sortOrder: '36', isActive: '1'});
  db.Country.create({countryCode:  'CC', countryName: 'Cocos (Keeling) Islands', sortOrder: '37', isActive: '1'});
  db.Country.create({countryCode:  'CD', countryName: 'Congo (DRC)', sortOrder: '38', isActive: '1'});
  db.Country.create({countryCode:  'CF', countryName: 'Central African Republic', sortOrder: '39', isActive: '1'});
  db.Country.create({countryCode:  'CG', countryName: 'Congo', sortOrder: '40', isActive: '1'});
  db.Country.create({countryCode:  'CH', countryName: 'Switzerland', sortOrder: '41', isActive: '1'});
  db.Country.create({countryCode:  'CI', countryName: 'Côte d Ivoire', sortOrder: '42', isActive: '1'});
  db.Country.create({countryCode:  'CK', countryName: 'Cook Islands', sortOrder: '43', isActive: '1'});
  db.Country.create({countryCode:  'CL', countryName: 'Chile', sortOrder: '44', isActive: '1'});
  db.Country.create({countryCode:  'CM', countryName: 'Cameroon', sortOrder: '45', isActive: '1'});
  db.Country.create({countryCode:  'CN', countryName: 'China', sortOrder: '46', isActive: '1'});
  db.Country.create({countryCode:  'CO', countryName: 'Colombia', sortOrder: '47', isActive: '1'});
  db.Country.create({countryCode:  'CR', countryName: 'Costa Rica', sortOrder: '48', isActive: '1'});
  db.Country.create({countryCode:  'CS', countryName: 'Serbia and Montenegro', sortOrder: '49', isActive: '1'});
  db.Country.create({countryCode:  'CU', countryName: 'Cuba', sortOrder: '50', isActive: '1'});
  db.Country.create({countryCode:  'CV', countryName: 'Cape Verde', sortOrder: '51', isActive: '1'});
  db.Country.create({countryCode:  'CX', countryName: 'Christmas Island', sortOrder: '52', isActive: '1'});
  db.Country.create({countryCode:  'CY', countryName: 'Cyprus', sortOrder: '53', isActive: '1'});
  db.Country.create({countryCode:  'CZ', countryName: 'Czech Republic', sortOrder: '54', isActive: '1'});
  db.Country.create({countryCode:  'DE', countryName: 'Germany', sortOrder: '55', isActive: '1'});
  db.Country.create({countryCode:  'DJ', countryName: 'Djibouti', sortOrder: '56', isActive: '1'});
  db.Country.create({countryCode:  'DK', countryName: 'Denmark', sortOrder: '57', isActive: '1'});
  db.Country.create({countryCode:  'DM', countryName: 'Dominica', sortOrder: '58', isActive: '1'});
  db.Country.create({countryCode:  'DO', countryName: 'Dominican Republic', sortOrder: '59', isActive: '1'});
  db.Country.create({countryCode:  'DZ', countryName: 'Algeria', sortOrder: '60', isActive: '1'});
  db.Country.create({countryCode:  'EC', countryName: 'Ecuador', sortOrder: '61', isActive: '1'});
  db.Country.create({countryCode:  'EE', countryName: 'Estonia', sortOrder: '62', isActive: '1'});
  db.Country.create({countryCode:  'EG', countryName: 'Egypt', sortOrder: '63', isActive: '1'});
  db.Country.create({countryCode:  'ER', countryName: 'Eritrea', sortOrder: '64', isActive: '1'});
  db.Country.create({countryCode:  'ES', countryName: 'Spain', sortOrder: '65', isActive: '1'});
  db.Country.create({countryCode:  'ET', countryName: 'Ethiopia', sortOrder: '66', isActive: '1'});
  db.Country.create({countryCode:  'FI', countryName: 'Finland', sortOrder: '67', isActive: '1'});
  db.Country.create({countryCode:  'FJ', countryName: 'Fiji Islands', sortOrder: '68', isActive: '1'});
  db.Country.create({countryCode:  'FK', countryName: 'Falkland Islands (Islas Malvinas)', sortOrder: '69', isActive: '1'});
  db.Country.create({countryCode:  'FM', countryName: 'Micronesia', sortOrder: '70', isActive: '1'});
  db.Country.create({countryCode:  'FO', countryName: 'Faroe Islands', sortOrder: '71', isActive: '1'});
  db.Country.create({countryCode:  'FR', countryName: 'France', sortOrder: '72', isActive: '1'});
  db.Country.create({countryCode:  'GA', countryName: 'Gabon', sortOrder: '73', isActive: '1'});
  db.Country.create({countryCode:  'GB', countryName: 'United Kingdom', sortOrder: '74', isActive: '1'});
  db.Country.create({countryCode:  'GD', countryName: 'Grenada', sortOrder: '75', isActive: '1'});
  db.Country.create({countryCode:  'GE', countryName: 'Georgia', sortOrder: '76', isActive: '1'});
  db.Country.create({countryCode:  'GF', countryName: 'French Guiana', sortOrder: '77', isActive: '1'});
  db.Country.create({countryCode:  'GH', countryName: 'Ghana', sortOrder: '78', isActive: '1'});
  db.Country.create({countryCode:  'GI', countryName: 'Gibraltar', sortOrder: '79', isActive: '1'});
  db.Country.create({countryCode:  'GL', countryName: 'Greenland', sortOrder: '80', isActive: '1'});
  db.Country.create({countryCode:  'GM', countryName: 'Gambia, The', sortOrder: '81', isActive: '1'});
  db.Country.create({countryCode:  'GN', countryName: 'Guinea', sortOrder: '82', isActive: '1'});
  db.Country.create({countryCode:  'GP', countryName: 'Guadeloupe', sortOrder: '83', isActive: '1'});
  db.Country.create({countryCode:  'GQ', countryName: 'Equatorial Guinea', sortOrder: '84', isActive: '1'});
  db.Country.create({countryCode:  'GR', countryName: 'Greece', sortOrder: '85', isActive: '1'});
  db.Country.create({countryCode:  'GS', countryName: 'South Georgia and the South Sandwich Islands', sortOrder: '86', isActive: '1'});
  db.Country.create({countryCode:  'GT', countryName: 'Guatemala', sortOrder: '87', isActive: '1'});
  db.Country.create({countryCode:  'GU', countryName: 'Guam', sortOrder: '88', isActive: '1'});
  db.Country.create({countryCode:  'GW', countryName: 'Guinea-Bissau', sortOrder: '89', isActive: '1'});
  db.Country.create({countryCode:  'GY', countryName: 'Guyana', sortOrder: '90', isActive: '1'});
  db.Country.create({countryCode:  'HK', countryName: 'Hong Kong SAR', sortOrder: '91', isActive: '1'});
  db.Country.create({countryCode:  'HM', countryName: 'Heard Island and McDonald Islands', sortOrder: '92', isActive: '1'});
  db.Country.create({countryCode:  'HN', countryName: 'Honduras', sortOrder: '93', isActive: '1'});
  db.Country.create({countryCode:  'HR', countryName: 'Croatia', sortOrder: '94', isActive: '1'});
  db.Country.create({countryCode:  'HT', countryName: 'Haiti', sortOrder: '95', isActive: '1'});
  db.Country.create({countryCode:  'HU', countryName: 'Hungary', sortOrder: '96', isActive: '1'});
  db.Country.create({countryCode:  'ID', countryName: 'Indonesia', sortOrder: '97', isActive: '1'});
  db.Country.create({countryCode:  'IE', countryName: 'Ireland', sortOrder: '98', isActive: '1'});
  db.Country.create({countryCode:  'IL', countryName: 'Israel', sortOrder: '99', isActive: '1'});
  db.Country.create({countryCode:  'IN', countryName: 'India', sortOrder: '100', isActive: '1'});
  db.Country.create({countryCode:  'IO', countryName: 'British Indian Ocean Territory', sortOrder: '101', isActive: '1'});
  db.Country.create({countryCode:  'IQ', countryName: 'Iraq', sortOrder: '102', isActive: '1'});
  db.Country.create({countryCode:  'IR', countryName: 'Iran', sortOrder: '103', isActive: '1'});
  db.Country.create({countryCode:  'IS', countryName: 'Iceland', sortOrder: '104', isActive: '1'});
  db.Country.create({countryCode:  'IT', countryName: 'Italy', sortOrder: '105', isActive: '1'});
  db.Country.create({countryCode:  'JM', countryName: 'Jamaica', sortOrder: '106', isActive: '1'});
  db.Country.create({countryCode:  'JO', countryName: 'Jordan', sortOrder: '107', isActive: '1'});
  db.Country.create({countryCode:  'JP', countryName: 'Japan', sortOrder: '108', isActive: '1'});
  db.Country.create({countryCode:  'KE', countryName: 'Kenya', sortOrder: '109', isActive: '1'});
  db.Country.create({countryCode:  'KG', countryName: 'Kyrgyzstan', sortOrder: '110', isActive: '1'});
  db.Country.create({countryCode:  'KH', countryName: 'Cambodia', sortOrder: '111', isActive: '1'});
  db.Country.create({countryCode:  'KI', countryName: 'Kiribati', sortOrder: '112', isActive: '1'});
  db.Country.create({countryCode:  'KM', countryName: 'Comoros', sortOrder: '113', isActive: '1'});
  db.Country.create({countryCode:  'KN', countryName: 'Saint Kitts and Nevis', sortOrder: '114', isActive: '1'});
  db.Country.create({countryCode:  'KP', countryName: 'North Korea', sortOrder: '115', isActive: '1'});
  db.Country.create({countryCode:  'KR', countryName: 'Korea', sortOrder: '116', isActive: '1'});
  db.Country.create({countryCode:  'KW', countryName: 'Kuwait', sortOrder: '117', isActive: '1'});
  db.Country.create({countryCode:  'KY', countryName: 'Cayman Islands', sortOrder: '118', isActive: '1'});
  db.Country.create({countryCode:  'KZ', countryName: 'Kazakhstan', sortOrder: '119', isActive: '1'});
  db.Country.create({countryCode:  'LA', countryName: 'Laos', sortOrder: '120', isActive: '1'});
  db.Country.create({countryCode:  'LB', countryName: 'Lebanon', sortOrder: '121', isActive: '1'});
  db.Country.create({countryCode:  'LC', countryName: 'Saint Lucia', sortOrder: '122', isActive: '1'});
  db.Country.create({countryCode:  'LI', countryName: 'Liechtenstein', sortOrder: '123', isActive: '1'});
  db.Country.create({countryCode:  'LK', countryName: 'Sri Lanka', sortOrder: '124', isActive: '1'});
  db.Country.create({countryCode:  'LR', countryName: 'Liberia', sortOrder: '125', isActive: '1'});
  db.Country.create({countryCode:  'LS', countryName: 'Lesotho', sortOrder: '126', isActive: '1'});
  db.Country.create({countryCode:  'LT', countryName: 'Lithuania', sortOrder: '127', isActive: '1'});
  db.Country.create({countryCode:  'LU', countryName: 'Luxembourg', sortOrder: '128', isActive: '1'});
  db.Country.create({countryCode:  'LV', countryName: 'Latvia', sortOrder: '129', isActive: '1'});
  db.Country.create({countryCode:  'LY', countryName: 'Libya', sortOrder: '130', isActive: '1'});
  db.Country.create({countryCode:  'MA', countryName: 'Morocco', sortOrder: '131', isActive: '1'});
  db.Country.create({countryCode:  'MC', countryName: 'Monaco', sortOrder: '132', isActive: '1'});
  db.Country.create({countryCode:  'MD', countryName: 'Moldova', sortOrder: '133', isActive: '1'});
  db.Country.create({countryCode:  'MG', countryName: 'Madagascar', sortOrder: '134', isActive: '1'});
  db.Country.create({countryCode:  'MH', countryName: 'Marshall Islands', sortOrder: '135', isActive: '1'});
  db.Country.create({countryCode:  'MK', countryName: 'Macedonia, Former Yugoslav Republic of', sortOrder: '136', isActive: '1'});
  db.Country.create({countryCode:  'ML', countryName: 'Mali', sortOrder: '137', isActive: '1'});
  db.Country.create({countryCode:  'MM', countryName: 'Myanmar', sortOrder: '138', isActive: '1'});
  db.Country.create({countryCode:  'MN', countryName: 'Mongolia', sortOrder: '139', isActive: '1'});
  db.Country.create({countryCode:  'MO', countryName: 'Macao SAR', sortOrder: '140', isActive: '1'});
  db.Country.create({countryCode:  'MP', countryName: 'Northern Mariana Islands', sortOrder: '141', isActive: '1'});
  db.Country.create({countryCode:  'MQ', countryName: 'Martinique', sortOrder: '142', isActive: '1'});
  db.Country.create({countryCode:  'MR', countryName: 'Mauritania', sortOrder: '143', isActive: '1'});
  db.Country.create({countryCode:  'MS', countryName: 'Montserrat', sortOrder: '144', isActive: '1'});
  db.Country.create({countryCode:  'MT', countryName: 'Malta', sortOrder: '145', isActive: '1'});
  db.Country.create({countryCode:  'MU', countryName: 'Mauritius', sortOrder: '146', isActive: '1'});
  db.Country.create({countryCode:  'MV', countryName: 'Maldives', sortOrder: '147', isActive: '1'});
  db.Country.create({countryCode:  'MW', countryName: 'Malawi', sortOrder: '148', isActive: '1'});
  db.Country.create({countryCode:  'MX', countryName: 'Mexico', sortOrder: '149', isActive: '1'});
  db.Country.create({countryCode:  'MY', countryName: 'Malaysia', sortOrder: '150', isActive: '1'});
  db.Country.create({countryCode:  'MZ', countryName: 'Mozambique', sortOrder: '151', isActive: '1'});
  db.Country.create({countryCode:  'NA', countryName: 'Namibia', sortOrder: '152', isActive: '1'});
  db.Country.create({countryCode:  'NC', countryName: 'New Caledonia', sortOrder: '153', isActive: '1'});
  db.Country.create({countryCode:  'NE', countryName: 'Niger', sortOrder: '154', isActive: '1'});
  db.Country.create({countryCode:  'NF', countryName: 'Norfolk Island', sortOrder: '155', isActive: '1'});
  db.Country.create({countryCode:  'NG', countryName: 'Nigeria', sortOrder: '156', isActive: '1'});
  db.Country.create({countryCode:  'NI', countryName: 'Nicaragua', sortOrder: '157', isActive: '1'});
  db.Country.create({countryCode:  'NL', countryName: 'Netherlands', sortOrder: '158', isActive: '1'});
  db.Country.create({countryCode:  'NO', countryName: 'Norway', sortOrder: '159', isActive: '1'});
  db.Country.create({countryCode:  'NP', countryName: 'Nepal', sortOrder: '160', isActive: '1'});
  db.Country.create({countryCode:  'NR', countryName: 'Nauru', sortOrder: '161', isActive: '1'});
  db.Country.create({countryCode:  'NU', countryName: 'Niue', sortOrder: '162', isActive: '1'});
  db.Country.create({countryCode:  'NZ', countryName: 'New Zealand', sortOrder: '163', isActive: '1'});
  db.Country.create({countryCode:  'OM', countryName: 'Oman', sortOrder: '164', isActive: '1'});
  db.Country.create({countryCode:  'PA', countryName: 'Panama', sortOrder: '165', isActive: '1'});
  db.Country.create({countryCode:  'PE', countryName: 'Peru', sortOrder: '166', isActive: '1'});
  db.Country.create({countryCode:  'PF', countryName: 'French Polynesia', sortOrder: '167', isActive: '1'});
  db.Country.create({countryCode:  'PG', countryName: 'Papua New Guinea', sortOrder: '168', isActive: '1'});
  db.Country.create({countryCode:  'PH', countryName: 'Philippines', sortOrder: '169', isActive: '1'});
  db.Country.create({countryCode:  'PK', countryName: 'Pakistan', sortOrder: '170', isActive: '1'});
  db.Country.create({countryCode:  'PL', countryName: 'Poland', sortOrder: '171', isActive: '1'});
  db.Country.create({countryCode:  'PM', countryName: 'Saint Pierre and Miquelon', sortOrder: '172', isActive: '1'});
  db.Country.create({countryCode:  'PN', countryName: 'Pitcairn Islands', sortOrder: '173', isActive: '1'});
  db.Country.create({countryCode:  'PR', countryName: 'Puerto Rico', sortOrder: '174', isActive: '1'});
  db.Country.create({countryCode:  'PS', countryName: 'Palestinian Authority', sortOrder: '175', isActive: '1'});
  db.Country.create({countryCode:  'PT', countryName: 'Portugal', sortOrder: '176', isActive: '1'});
  db.Country.create({countryCode:  'PW', countryName: 'Palau', sortOrder: '177', isActive: '1'});
  db.Country.create({countryCode:  'PY', countryName: 'Paraguay', sortOrder: '178', isActive: '1'});
  db.Country.create({countryCode:  'QA', countryName: 'Qatar', sortOrder: '179', isActive: '1'});
  db.Country.create({countryCode:  'RE', countryName: 'Réunion', sortOrder: '180', isActive: '1'});
  db.Country.create({countryCode:  'RO', countryName: 'Romania', sortOrder: '181', isActive: '1'});
  db.Country.create({countryCode:  'RU', countryName: 'Russia', sortOrder: '182', isActive: '1'});
  db.Country.create({countryCode:  'RW', countryName: 'Rwanda', sortOrder: '183', isActive: '1'});
  db.Country.create({countryCode:  'SA', countryName: 'Saudi Arabia', sortOrder: '184', isActive: '1'});
  db.Country.create({countryCode:  'SB', countryName: 'Solomon Islands', sortOrder: '185', isActive: '1'});
  db.Country.create({countryCode:  'SC', countryName: 'Seychelles', sortOrder: '186', isActive: '1'});
  db.Country.create({countryCode:  'SD', countryName: 'Sudan', sortOrder: '187', isActive: '1'});
  db.Country.create({countryCode:  'SE', countryName: 'Sweden', sortOrder: '188', isActive: '1'});
  db.Country.create({countryCode:  'SG', countryName: 'Singapore', sortOrder: '189', isActive: '1'});
  db.Country.create({countryCode:  'SH', countryName: 'Saint Helena', sortOrder: '190', isActive: '1'});
  db.Country.create({countryCode:  'SI', countryName: 'Slovenia', sortOrder: '191', isActive: '1'});
  db.Country.create({countryCode:  'SJ', countryName: 'Svalbard and Jan Mayen', sortOrder: '192', isActive: '1'});
  db.Country.create({countryCode:  'SK', countryName: 'Slovakia', sortOrder: '193', isActive: '1'});
  db.Country.create({countryCode:  'SL', countryName: 'Sierra Leone', sortOrder: '194', isActive: '1'});
  db.Country.create({countryCode:  'SM', countryName: 'San Marino', sortOrder: '195', isActive: '1'});
  db.Country.create({countryCode:  'SN', countryName: 'Senegal', sortOrder: '196', isActive: '1'});
  db.Country.create({countryCode:  'SO', countryName: 'Somalia', sortOrder: '197', isActive: '1'});
  db.Country.create({countryCode:  'SR', countryName: 'Suriname', sortOrder: '198', isActive: '1'});
  db.Country.create({countryCode:  'ST', countryName: 'São Tomé and Príncipe', sortOrder: '199', isActive: '1'});
  db.Country.create({countryCode:  'SV', countryName: 'El Salvador', sortOrder: '200', isActive: '1'});
  db.Country.create({countryCode:  'SY', countryName: 'Syria', sortOrder: '201', isActive: '1'});
  db.Country.create({countryCode:  'SZ', countryName: 'Swaziland', sortOrder: '202', isActive: '1'});
  db.Country.create({countryCode:  'TC', countryName: 'Turks and Caicos Islands', sortOrder: '203', isActive: '1'});
  db.Country.create({countryCode:  'TD', countryName: 'Chad', sortOrder: '204', isActive: '1'});
  db.Country.create({countryCode:  'TF', countryName: 'French Southern and Antarctic Lands', sortOrder: '205', isActive: '1'});
  db.Country.create({countryCode:  'TG', countryName: 'Togo', sortOrder: '206', isActive: '1'});
  db.Country.create({countryCode:  'TH', countryName: 'Thailand', sortOrder: '207', isActive: '1'});
  db.Country.create({countryCode:  'TJ', countryName: 'Tajikistan', sortOrder: '208', isActive: '1'});
  db.Country.create({countryCode:  'TK', countryName: 'Tokelau', sortOrder: '209', isActive: '1'});
  db.Country.create({countryCode:  'TL', countryName: 'Timor-Leste', sortOrder: '210', isActive: '1'});
  db.Country.create({countryCode:  'TM', countryName: 'Turkmenistan', sortOrder: '211', isActive: '1'});
  db.Country.create({countryCode:  'TN', countryName: 'Tunisia', sortOrder: '212', isActive: '1'});
  db.Country.create({countryCode:  'TO', countryName: 'Tonga', sortOrder: '213', isActive: '1'});
  db.Country.create({countryCode:  'TR', countryName: 'Turkey', sortOrder: '214', isActive: '1'});
  db.Country.create({countryCode:  'TT', countryName: 'Trinidad and Tobago', sortOrder: '215', isActive: '1'});
  db.Country.create({countryCode:  'TV', countryName: 'Tuvalu', sortOrder: '216', isActive: '1'});
  db.Country.create({countryCode:  'TW', countryName: 'Taiwan', sortOrder: '217', isActive: '1'});
  db.Country.create({countryCode:  'TZ', countryName: 'Tanzania', sortOrder: '218', isActive: '1'});
  db.Country.create({countryCode:  'UA', countryName: 'Ukraine', sortOrder: '219', isActive: '1'});
  db.Country.create({countryCode:  'UG', countryName: 'Uganda', sortOrder: '220', isActive: '1'});
  db.Country.create({countryCode:  'UM', countryName: 'U.S. Minor Outlying Islands', sortOrder: '221', isActive: '1'});
  db.Country.create({countryCode:  'US', countryName: 'United States', sortOrder: '222', isActive: '1'});
  db.Country.create({countryCode:  'UY', countryName: 'Uruguay', sortOrder: '223', isActive: '1'});
  db.Country.create({countryCode:  'UZ', countryName: 'Uzbekistan', sortOrder: '224', isActive: '1'});
  db.Country.create({countryCode:  'VA', countryName: 'Vatican City', sortOrder: '225', isActive: '1'});
  db.Country.create({countryCode:  'VC', countryName: 'Saint Vincent and the Grenadine', sortOrder: '226', isActive: '1'});
  db.Country.create({countryCode:  'VE', countryName: 'Venezuela', sortOrder: '227', isActive: '1'});
  db.Country.create({countryCode:  'VG', countryName: 'Virgin Islands, British', sortOrder: '228', isActive: '1'});
  db.Country.create({countryCode:  'VI', countryName: 'Virgin Islands, U.S.', sortOrder: '229', isActive: '1'});
  db.Country.create({countryCode:  'VN', countryName: 'Vietnam', sortOrder: '230', isActive: '1'});
  db.Country.create({countryCode:  'VU', countryName: 'Vanuatu', sortOrder: '231', isActive: '1'});
  db.Country.create({countryCode:  'WF', countryName: 'Wallis and Futuna', sortOrder: '232', isActive: '1'});
  db.Country.create({countryCode:  'WS', countryName: 'Samoa', sortOrder: '233', isActive: '1'});
  db.Country.create({countryCode:  'YE', countryName: 'Yemen', sortOrder: '234', isActive: '1'});
  db.Country.create({countryCode:  'YT', countryName: 'Mayotte', sortOrder: '235', isActive: '1'});
  db.Country.create({countryCode:  'ZA', countryName: 'South Africa', sortOrder: '236', isActive: '1'});
  db.Country.create({countryCode:  'ZM', countryName: 'Zambia', sortOrder: '237', isActive: '1'});
  db.Country.create({countryCode:  'ZW', countryName: 'Zimbabwe', sortOrder: '238', isActive: '1'});


};