module.exports = function(db) {
  db.StateProvince.create({stateProvinceCode:  'AB ', stateProvinceName: 'Alberta', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '1', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'AK ', stateProvinceName: 'Alaska', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '2', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'AL ', stateProvinceName: 'Alabama', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '3', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'AR ', stateProvinceName: 'Arkansas', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '4', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'AS ', stateProvinceName: 'American Samoa', countryCode: 'AS', isOnlyState: true,  territoryId: '2', sortOrder: '5', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'AZ ', stateProvinceName: 'Arizona', countryCode: 'US', isOnlyState: false,  territoryId: '4', sortOrder: '6', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'BC ', stateProvinceName: 'British Columbia', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '7', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'BY ', stateProvinceName: 'Bayern', countryCode: 'DE', isOnlyState: false,  territoryId: '8', sortOrder: '8', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'CA ', stateProvinceName: 'California', countryCode: 'US', isOnlyState: false,  territoryId: '4', sortOrder: '9', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'CO ', stateProvinceName: 'Colorado', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '10', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'CT ', stateProvinceName: 'Connecticut', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '11', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'DC ', stateProvinceName: 'District of Columbia', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '12', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'DE ', stateProvinceName: 'Delaware', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '13', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'ENG', stateProvinceName: 'England', countryCode: 'GB', isOnlyState: true,  territoryId: '10', sortOrder: '14', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'FL ', stateProvinceName: 'Florida', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '15', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'FM ', stateProvinceName: 'Micronesia', countryCode: 'FM', isOnlyState: true,  territoryId: '9', sortOrder: '16', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'GA ', stateProvinceName: 'Georgia', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '17', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'GU ', stateProvinceName: 'Guam', countryCode: 'US', isOnlyState: false,  territoryId: '4', sortOrder: '18', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'HE ', stateProvinceName: 'Hessen', countryCode: 'DE', isOnlyState: false,  territoryId: '8', sortOrder: '19', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'HH ', stateProvinceName: 'Hamburg', countryCode: 'DE', isOnlyState: false,  territoryId: '8', sortOrder: '20', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'HI ', stateProvinceName: 'Hawaii', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '21', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'IA ', stateProvinceName: 'Iowa', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '22', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'ID ', stateProvinceName: 'Idaho', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '23', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'IL ', stateProvinceName: 'Illinois', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '24', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'IN ', stateProvinceName: 'Indiana', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '25', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'KS ', stateProvinceName: 'Kansas', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '26', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'KY ', stateProvinceName: 'Kentucky', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '27', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'LA ', stateProvinceName: 'Louisiana', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '28', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'LB ', stateProvinceName: 'Labrador', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '29', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MA ', stateProvinceName: 'Massachusetts', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '30', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MB ', stateProvinceName: 'Manitoba', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '31', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MD ', stateProvinceName: 'Maryland', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '32', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'ME ', stateProvinceName: 'Maine', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '33', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MH ', stateProvinceName: 'Marshall Islands', countryCode: 'MH', isOnlyState: true,  territoryId: '9', sortOrder: '34', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MI ', stateProvinceName: 'Michigan', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '35', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MN ', stateProvinceName: 'Minnesota', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '36', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MO ', stateProvinceName: 'Missouri', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '37', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MP ', stateProvinceName: 'Northern Mariana Islands', countryCode: 'MP', isOnlyState: true,  territoryId: '9', sortOrder: '38', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MS ', stateProvinceName: 'Mississippi', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '39', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'MT ', stateProvinceName: 'Montana', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '40', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NB ', stateProvinceName: 'Brunswick', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '41', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NC ', stateProvinceName: 'North Carolina', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '42', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'ND ', stateProvinceName: 'North Dakota', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '43', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NE ', stateProvinceName: 'Nebraska', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '44', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NF ', stateProvinceName: 'Newfoundland', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '45', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NH ', stateProvinceName: 'New Hampshire', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '46', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NJ ', stateProvinceName: 'New Jersey', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '47', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NM ', stateProvinceName: 'New Mexico', countryCode: 'US', isOnlyState: false,  territoryId: '4', sortOrder: '48', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NS ', stateProvinceName: 'Nova Scotia', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '49', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NSW', stateProvinceName: 'New South Wales', countryCode: 'AU', isOnlyState: false,  territoryId: '9', sortOrder: '50', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NT ', stateProvinceName: 'Northwest Territories', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '51', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NV ', stateProvinceName: 'Nevada', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '52', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NW ', stateProvinceName: 'Nordrhein-Westfalen', countryCode: 'DE', isOnlyState: false,  territoryId: '8', sortOrder: '53', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'NY ', stateProvinceName: 'New York', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '54', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'OH ', stateProvinceName: 'Ohio', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '55', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'OK ', stateProvinceName: 'Oklahoma', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '56', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'ON ', stateProvinceName: 'Ontario', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '57', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'OR ', stateProvinceName: 'Oregon', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '58', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'PA ', stateProvinceName: 'Pennsylvania', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '59', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'PE ', stateProvinceName: 'Prince Edward Island', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '60', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'PR ', stateProvinceName: 'Puerto Rico', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '61', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'PW ', stateProvinceName: 'Palau', countryCode: 'PW', isOnlyState: true,  territoryId: '9', sortOrder: '62', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'QC ', stateProvinceName: 'Quebec', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '63', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'QLD', stateProvinceName: 'Queensland', countryCode: 'AU', isOnlyState: false,  territoryId: '9', sortOrder: '64', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'RI ', stateProvinceName: 'Rhode Island', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '65', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'SA ', stateProvinceName: 'South Australia', countryCode: 'AU', isOnlyState: false,  territoryId: '9', sortOrder: '66', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'SC ', stateProvinceName: 'South Carolina', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '67', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'SD ', stateProvinceName: 'South Dakota', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '68', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'SK ', stateProvinceName: 'Saskatchewan', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '69', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'SL ', stateProvinceName: 'Saarland', countryCode: 'DE', isOnlyState: false,  territoryId: '8', sortOrder: '70', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'TAS', stateProvinceName: 'Tasmania', countryCode: 'AU', isOnlyState: false,  territoryId: '9', sortOrder: '71', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'TN ', stateProvinceName: 'Tennessee', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '72', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'TX ', stateProvinceName: 'Texas', countryCode: 'US', isOnlyState: false,  territoryId: '4', sortOrder: '73', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'UT ', stateProvinceName: 'Utah', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '74', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'VA ', stateProvinceName: 'Virginia', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '75', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'VI ', stateProvinceName: 'Virgin Islands', countryCode: 'VI', isOnlyState: true,  territoryId: '5', sortOrder: '76', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'VIC', stateProvinceName: 'Victoria', countryCode: 'AU', isOnlyState: false,  territoryId: '9', sortOrder: '77', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'VT ', stateProvinceName: 'Vermont', countryCode: 'US', isOnlyState: false,  territoryId: '1', sortOrder: '78', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'WA ', stateProvinceName: 'Washington', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '79', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'WI ', stateProvinceName: 'Wisconsin', countryCode: 'US', isOnlyState: false,  territoryId: '3', sortOrder: '80', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'WV ', stateProvinceName: 'West Virginia', countryCode: 'US', isOnlyState: false,  territoryId: '5', sortOrder: '81', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'WY ', stateProvinceName: 'Wyoming', countryCode: 'US', isOnlyState: false,  territoryId: '2', sortOrder: '82', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'YT ', stateProvinceName: 'Yukon Territory', countryCode: 'CA', isOnlyState: false,  territoryId: '6', sortOrder: '83', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'FR ', stateProvinceName: 'France', countryCode: 'FR', isOnlyState: true,  territoryId: '7', sortOrder: '84', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'BB ', stateProvinceName: 'Brandenburg', countryCode: 'DE', isOnlyState: false,  territoryId: '8', sortOrder: '85', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  'SN ', stateProvinceName: 'Saxony', countryCode: 'DE', isOnlyState: false,  territoryId: '8', sortOrder: '86', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '01 ', stateProvinceName: 'Ain', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '87', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '02 ', stateProvinceName: 'Aisne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '88', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '03 ', stateProvinceName: 'Allier', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '89', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '04 ', stateProvinceName: 'Alpes-de-Haute Provence', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '90', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '05 ', stateProvinceName: 'Alpes (Haute)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '91', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '06 ', stateProvinceName: 'Alpes-Maritimes', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '92', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '07 ', stateProvinceName: 'Ardèche', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '93', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '08 ', stateProvinceName: 'Ardennes', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '94', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '09 ', stateProvinceName: 'Ariège', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '95', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '10 ', stateProvinceName: 'Aube', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '96', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '11 ', stateProvinceName: 'Aude', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '97', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '12 ', stateProvinceName: 'Aveyron', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '98', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '13 ', stateProvinceName: 'Bouches du Rhône', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '99', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '14 ', stateProvinceName: 'Calvados', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '100', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '15 ', stateProvinceName: 'Cantal', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '101', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '16 ', stateProvinceName: 'Charente', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '102', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '17 ', stateProvinceName: 'Charente-Maritime', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '103', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '18 ', stateProvinceName: 'Cher', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '104', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '19 ', stateProvinceName: 'Corrèze', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '105', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '20 ', stateProvinceName: 'Corse', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '106', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '21 ', stateProvinceName: 'Côte d Or', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '107', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '22 ', stateProvinceName: 'Côtes-d Armor', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '108', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '23 ', stateProvinceName: 'Creuse', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '109', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '24 ', stateProvinceName: 'Dordogne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '110', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '25 ', stateProvinceName: 'Toubs', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '111', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '26 ', stateProvinceName: 'Drôme', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '112', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '27 ', stateProvinceName: 'Eure', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '113', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '28 ', stateProvinceName: 'Eure et Loir', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '114', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '29 ', stateProvinceName: 'Finistère', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '115', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '30 ', stateProvinceName: 'Gard', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '116', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '31 ', stateProvinceName: 'Garonne (Haute)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '117', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '32 ', stateProvinceName: 'Gers', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '118', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '33 ', stateProvinceName: 'Gironde', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '119', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '34 ', stateProvinceName: 'Hérault', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '120', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '35 ', stateProvinceName: 'Ille et Vilaine', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '121', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '36 ', stateProvinceName: 'Indre', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '122', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '37 ', stateProvinceName: 'Indre et Loire', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '123', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '38 ', stateProvinceName: 'Isère', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '124', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '39 ', stateProvinceName: 'Jura', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '125', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '40 ', stateProvinceName: 'Landes', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '126', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '41 ', stateProvinceName: 'Loir et Cher', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '127', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '42 ', stateProvinceName: 'Loire', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '128', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '43 ', stateProvinceName: 'Loire (Haute)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '129', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '44 ', stateProvinceName: 'Loire Atlantique', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '130', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '45 ', stateProvinceName: 'Loiret', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '131', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '46 ', stateProvinceName: 'Lot', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '132', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '47 ', stateProvinceName: 'Lot et Garonne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '133', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '48 ', stateProvinceName: 'Lozère', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '134', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '49 ', stateProvinceName: 'Maine et Loire', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '135', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '50 ', stateProvinceName: 'Manche', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '136', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '51 ', stateProvinceName: 'Marne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '137', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '52 ', stateProvinceName: 'Marne (Haute)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '138', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '53 ', stateProvinceName: 'Mayenne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '139', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '54 ', stateProvinceName: 'Meurthe et Moselle', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '140', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '55 ', stateProvinceName: 'Meuse', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '141', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '56 ', stateProvinceName: 'Morbihan', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '142', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '57 ', stateProvinceName: 'Moselle', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '143', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '58 ', stateProvinceName: 'Nièvre', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '144', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '59 ', stateProvinceName: 'Nord', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '145', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '60 ', stateProvinceName: 'Oise', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '146', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '61 ', stateProvinceName: 'Orne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '147', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '62 ', stateProvinceName: 'Pas de Calais', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '148', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '63 ', stateProvinceName: 'Puy de Dôme', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '149', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '64 ', stateProvinceName: 'Pyrénées Atlantiques', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '150', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '65 ', stateProvinceName: 'Pyrénées (Hautes)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '151', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '66 ', stateProvinceName: 'Pyrénées Orientales', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '152', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '67 ', stateProvinceName: 'Rhin (Bas)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '153', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '68 ', stateProvinceName: 'Rhin (Haut)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '154', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '69 ', stateProvinceName: 'Rhône', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '155', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '70 ', stateProvinceName: 'Saône (Haute)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '156', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '71 ', stateProvinceName: 'Saône et Loire', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '157', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '72 ', stateProvinceName: 'Sarthe', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '158', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '73 ', stateProvinceName: 'Savoie', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '159', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '74 ', stateProvinceName: 'Savoie Haute', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '160', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '75 ', stateProvinceName: 'Seine (Paris)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '161', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '76 ', stateProvinceName: 'Seine Maritime', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '162', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '77 ', stateProvinceName: 'Seine et Marne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '163', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '78 ', stateProvinceName: 'Yveline', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '164', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '79 ', stateProvinceName: 'Sèvres (Deux)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '165', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '80 ', stateProvinceName: 'Somme', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '166', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '81 ', stateProvinceName: 'Tarne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '167', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '82 ', stateProvinceName: 'Tarne et Garonne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '168', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '83 ', stateProvinceName: 'Var', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '169', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '84 ', stateProvinceName: 'Vaucluse', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '170', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '85 ', stateProvinceName: 'La Vendée', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '171', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '86 ', stateProvinceName: 'Vienne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '172', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '87 ', stateProvinceName: 'Vienne (Haute)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '173', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '88 ', stateProvinceName: 'Vosges', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '174', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '89 ', stateProvinceName: 'Yonne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '175', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '90 ', stateProvinceName: 'Belford (Territoire de)', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '176', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '91 ', stateProvinceName: 'Essonne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '177', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '92 ', stateProvinceName: 'Hauts de Seine', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '178', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '93 ', stateProvinceName: 'Seine Saint Denis', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '179', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '94 ', stateProvinceName: 'Val de Marne', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '180', isActive: '1'});
  db.StateProvince.create({stateProvinceCode:  '95 ', stateProvinceName: 'Val d Oise', countryCode: 'FR', isOnlyState: false,  territoryId: '7', sortOrder: '181', isActive: '1'});

};